spinnaker/spinnaker.io

themes/docsy-master/layouts/partials/footer.html
Adding the Netlify footer badge. We can change the color of the badge or swap to a phrase in the footer later once we decide on the final look/feel of spinnaker.io
=> docs(migraiton): add netlify footer badge

content/en/docs/guides/developer/plugin-creators/stage-plugin-walkthrough.md, layouts/shortcodes/alpha.html
Shortcode to replace the Jekyll "alpha" include.
Usage:
Replace Jekyll  `{% include alpha version="1.19.4" %}` with `{{< alpha version="1.19.4" >}}`
Rendered output:
Page with alpha shortcode:  https://deploy-preview-52--spinnaker-io.netlify.app/docs/guides/developer/plugin-creators/stage-plugin-walkthrough/
=> docs(shortcodes): add "alpha" shortcode

layouts/partials/footer.html, themes/docsy-master/layouts/partials/footer.html
Move custom footer code out of theme and into project layouts folder.
This overrides PR https://github.com/spinnaker/spinnaker.io/pull/1
Overriding Docsy theme elements is best done in the project, not in the theme itself, as the Docsy docs recommend. Changing the theme directly could result in difficulties when we need to update the theme,  apply patches, update Hugo, etc.
https://www.docsy.dev/docs/adding-content/lookandfeel/#customizing-templates
=> docs(theme-fix): move custom footer out of theme

layouts/partials/hooks/head-end.html
Bootstrap and Docsy generate the meta description tag as `meta itemprop="description" content="page description"` but search engines look for `meta name='description' ...`. This is a workaround until the issue is 
addressed by the underlying frameworks.
I traced the meta tags definitions to `themes/docsy/assets/vendor/bootstrap/site/_includes/header.html`. Emailed the Docsy users list asking why` <meta name="description"` is generated as `<meta itemprop="description"'` but haven't had a response. For SEO, add correct `<meta name="description"` to `layouts/partials/hooks/head-end.html`. 
To test, do a "view page source" in your browser and look for `<meta name="description"`. If the page contains `description` in the front matter, that is used for content. Otherwise, the value for …
=> docs(seo): add logic to generate meta "description" tag

content/en/docs/guides/user/managed-delivery/managed-delivery-overview.md
Managed Delivery hasn't been in Alpha for more than a year now. We're running it in production at Netflix for hundreds of apps. Just correcting the docs to reflect that.
=> fix(docs): Remove Alpha comments from MD overview

content/en/docs/guides/user/pipeline/expressions/_index.md
The page was renamed in the move. Added redirect for `/guides/user/pipeline-expressions/`
=> docs(fix): add redirect from old URL

layouts/partials/hero-homepage.html
I corrected a line that had `when` instead of `if`. Before the correction, the site wouldn't compile if `.Params.news_link` was defined.
=> docs(site): Fix logic error

content/en/docs/setup/other_config/ci/travis.md
Corrected misspelling of "continuous"
=> Corrected misspelling of "continuous" in travis.md

content/en/docs/setup/other_config/features/notifications/index.md
On the notifications page, the Generated e-mail table isn't displaying on the generated output, nor in raw Markdown. Little whitespace fix should fix the table.
Source: https://spinnaker.io/docs/setup/other_config/features/notifications/#email
**Generated with bug:**
| Before | After
| --- | --- |
| <img width="1255" alt="image" src="https://user-images.githubusercontent.com/33203301/131937047-57ec07e3-4afb-4341-839b-7ada20a67bd2.png"> | <img width="984" alt="image" src="https://user-images.githubusercontent.com/33203301/131937318-36c10724-a1d8-4439-a5f2-46fdb7ec668f.png"> |
=> Fix e-mail table on Notifications page

content/en/docs/setup/install/providers/kubernetes-v2/aws-eks.md
The service-account.yaml file is referred to but there is no mention of what it should actually contain. This is not very complex, but it very much breaks the flow of the install and causes you to have to break out and look up the correct syntax for a service account, whether it requires RBAC etc. 
Added a link to the RBAC notes also to help on that front.
=> Add example for service-account,yaml

content/en/docs/releases/next-release-preview/index.md
Wanted to highlight the addition of shared managed service accounts in the next release:
https://github.com/spinnaker/orca/pull/4083
https://github.com/spinnaker/front50/pull/1022
We've seen a huge improvement in `fiat` role sync and auth calls since implementing this change!
=> docs(releases): Add shared managed service account to preview

content/en/docs/reference/halyard/custom.md
The field nodeSelectors does not propagate the changes to the pod. Per the kubernetes docs, the field is nodeSelector: and not nodeSelectors:. Suggesting this change after testing it out.
=> docs(fix): Updated typo from nodeSelectors to nodeSelector

content/en/docs/setup/install/providers/kubernetes-v2/_index.md, content/en/docs/setup/install/providers/kubernetes-v2/k8s-provider.md, content/en/docs/setup/install/providers/kubernetes.md
After adding a statefulset application, I realized on the clusters page that I cannot open the details panel. It's because the endpoint (`https://spinnaker/manifests/de-prod/auth/statefulSet%20app-name`) returns 403 Forbidden.
```
{
"timestamp": 1633679782550,
"status": 403,
"error": "Forbidden",
"message": "403 ",
"body": "{\"error\":\"Forbidden\",\"message\":\"Access is denied\",\"status\":403,\"timestamp\":\"2021-10-08T07:56:22.542+00:00\"}",
"url": "http://spin-clouddriver.platform:7002/manifests/de-prod/auth/statefulSet%20app-name"
}
```
This PR extends the role to cover stateful set actions.
And while there,
* Aligns resources under `apps` and `extensions` API groups.
* Drops unnecessary `app` API Group.
=> Extend Kubernetes role to cover statefulsets

content/en/docs/reference/ref-artifacts/_index.md
Current page https://spinnaker.io/docs/reference/ref-artifacts/#expected-artifacts shows `{% include figure image_path=”./expected-artifact-git...`
=> Fix expected artifact embedding

content/en/docs/reference/architecture/microservices-overview.md
Current link seem to be: https://spinnaker.io/docs/community/contributing/code/developer-guides/service-overviews/orca/
=> docs(fix): fix link to Orca from microservices-overview.md

content/en/docs/setup/other_config/accounts/index.md
This adds documentation for recently added features in Gate and
Clouddriver.
Related to https://github.com/spinnaker/spinnaker/issues/6525
=> docs(setup): Add Clouddriver Account Management

content/en/docs/guides/developer/plugin-creator/plugin-frontend.md
current links in plugin-frontend.md: 
- https://spinnaker.io/docs/guides/user/plugins/index
- https://spinnaker.io/docs/guides/user/plugins/
=> docs(fix): fix bronken links to path guides/user/plugins-users/ 

content/en/docs/community/contributing/code/developer-guides/dev-env/kork-library.md
The group id of kork has been changed from com.netflix.spinnaker.kork to io.spinnaker.kork in [this commit ](https://github.com/spinnaker/kork/commit/1d46c68eb50e7cc109f94930c421aa3c8a623350#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R29)but the same is not reflecting in the documentation hence this PR. Also updated gradlew command to include version.
=> doc(fix/kork): Update instructions to build and use kork in local development.

content/en/docs/releases/release-manager-runbook/index.md, content/en/docs/releases/versions.md
- Java 11 was migrated to some time back.
- Halyard version notices are no longer relevant. The Halyard BOM and regular Version release notes advise if a new Halyard version is required.
- `spin` CLI release process has changed with GHA.
=> docs(runbook): Update Runbook based on move to GHA

content/en/docs/reference/architecture/microservices-overview.md
The Keel port has been updated to 7010 (see PR links below).
Update the Keel port in the docs.
See:
https://github.com/spinnaker/keel/pull/1410
https://github.com/spinnaker/kustomization-base/pull/32
=> docs(fix): Update Keel port

content/en/docs/setup/other_config/server-group-launch-settings/aws-ec2/launch-templates-setup.md
Correcting `settings-local.js` for Deck to enable the Launch templates UI which leads to confusion how the configuration should be. For example https://github.com/spinnaker/spinnaker/issues/6614
=> docs(lt_deck_settings): Fixing the Deck settings for enabling Launch Templates

content/en/docs/releases/release-manager-runbook/index.md
Missed during https://github.com/spinnaker/spinnaker/issues/6678
=> docs(runbook): Update release manager runbook for no-gist flow

content/en/docs/guides/runbooks/caching-account-name-based-sharding.md
This documentation is related to the following PRs which are either merged in the previous releases or yet to be merged in the next release:
[feat(cats/sql): account name based sharding logic](https://github.com/spinnaker/clouddriver/pull/5295)
[feat(cats/redis): account name based sharding logic](https://github.com/spinnaker/clouddriver/pull/5382)
[refactor(cats/sql): made sharding configuration consistent](https://github.com/spinnaker/clouddriver/pull/5512)
=> Added caching-account-name-based-sharding documentation

content/en/docs/concepts/_index.md
It looks like the description is used as the opening paragraph of the page, which lead to the same paragraph appearing twice in a row.
=> Remove duplicate paragraph on “Concepts” page

assets/scss/docs.scss, static/js/promo-banner.js
Added conditionals to the DOCs table of contents css classes to bump down if banner is present and snap back to normal positioning when banner is removed.
=> DOCs table of contents positioning bug

content/en/2022/08/UserSecretMetadata.schema.json
This makes it easier to validate the format of user secret metadata by
verifying it matches a known schema.
Relates to https://github.com/spinnaker/kork/pull/974 and previous Kork PRs around user secrets.
=> Add JSON schema for UserSecretMetadata

content/en/docs/reference/halyard/secrets/secret-manager-secrets.md
Documentation for the recently added feature - Google Secret Manager implementation for secret engine.
https://github.com/spinnaker/kork/pull/960
=> Added documentation for Google Secret Manager secret engine 

content/en/docs/guides/user/plugins-users/_index.md
To include [spinnaker/plugins](https://github.com/spinnaker/plugins) repo under the reference section would be useful to the users who read through the plugin documentation.
=> Include official spinnaker plugins repo.

content/en/docs/releases/next-release-preview/index.md
Update the next release changelog with the changes done for introducing blue/green Kubernetes traffic management strategy
=> docs(kubernetes): Update the next release preview changelog

content/en/docs/reference/pipeline/expressions/_index.md
I came across a function that's useful but undocumented.
[Documentation](https://spinnaker.io/docs/reference/pipeline/expressions/)
[Code reference](https://github.com/spinnaker/orca/blob/3a0f45003cf80d441c6f044606234ee4d939029d/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/UrlExpressionFunctionProvider.java#L87)
=> Pipeline expressions - add undocumented readAllYaml function

content/en/docs/guides/user/pipeline/triggers/artifactory/_index.md, content/en/docs/guides/user/pipeline/triggers/bitbucket-events.md, content/en/docs/guides/user/pipeline/triggers/gcs/_index.md, content/en/docs/guides/user/pipeline/triggers/github/_index.md, content/en/docs/guides/user/pipeline/triggers/jenkins/_index.md, content/en/docs/guides/user/pipeline/triggers/pubsub/_index.md, content/en/docs/guides/user/pipeline/triggers/webhooks/_index.md
Scheduled for v1.30
- Code PR https://github.com/spinnaker/echo/pull/1219
- Removed `weight` front matter variable from pages in this section since weight had no value set; no weight == sort alphabetically
- Add new Bitbucket webhook events and how to use them as automated triggers in a pipeline
Fixes: https://github.com/spinnaker/spinnaker.io/issues/284
Deploy preview:  https://deploy-preview-285--spinnaker-io.netlify.app/docs/guides/user/pipeline/triggers/bitbucket-events/
=> docs(feat): Add Bitbucket webhook events as pipeline triggers

content/en/docs/community/_index.md
use the same link as on the home page
=> fix(slack): join.spinnaker.io no longer works

content/en/docs/guides/user/plugins-users/_index.md
Clean up "How to adda plugin to Spinnaker" section, which contained a TOC that was identical to the one rendered by Hugo.
=> docs(plugins): clean up Plugin User Guide section

content/en/docs/releases/release-manager-runbook/index.md
Buildtool now tags runnable services as part of release.
Halyard still needs to be re-tagged, update steps to use `regctl`.
Per: https://github.com/spinnaker/buildtool/pull/204
=> docs(release): Remove manual container tagging steps

content/en/docs/releases/next-release-preview/index.md
Update the next release changelog with the changes done to enable by default the "doNotEval SPeL expression" feature flag
=> docs(kork): Update the next release preview changelog

content/en/docs/releases/next-release-preview/index.md
document changes from https://github.com/spinnaker/front50/pull/1249
=> docs(changelog): document front50 config flags for optimizing cache refresh

content/en/docs/releases/next-release-preview/index.md
and how to configure orca to use it
changes from https://github.com/spinnaker/front50/pull/1251 and https://github.com/spinnaker/orca/pull/4448
=> docs(changelog): document front50's new getTriggeredPipelines endpoint

README.md, content/en/changelogs/1.30.0-changelog.md, content/en/docs/concepts/_index.md, content/en/docs/concepts/pipelines/_index.md, content/en/docs/guides/tutorials/codelabs/gce-source-to-prod/index.md, content/en/docs/guides/tutorials/codelabs/oci-source-to-prod/index.md, content/en/docs/guides/tutorials/codelabs/safe-deployments/index.md, content/en/docs/guides/user/kubernetes-v2/rollout-strategies/index.md, content/en/docs/reference/pipeline/stages/_index.md, content/en/docs/reference/providers/kubernetes.md, content/en/docs/setup/install/providers/kubernetes-v2/_index.md, content/en/docs/setup/install/providers/kubernetes-v2/k8s-provider.md, content/en/docs/setup/productionize/persistence/clouddriver-sql.md, data/about_copy.yaml, data/features.yaml
Users coming to Spinnaker are now more familiar with Blue/Green industry terminology than the Netflix specific phrasing Red/Black
- The Red/Black rollout strategy is marked as deprecated in the UI. Change done [here](https://github.com/spinnaker/deck/pull/9911)
- A Blue/Green rollout strategy is added that is functionally equivalent to the Red/Black rollout strategy. Changes done in [clouddriver](https://github.com/spinnaker/clouddriver/pull/5811) and [orca](https://github.com/spinnaker/orca/pull/4332)
- Introduce a pipeline validator in Front50 that validates if red/black is used when creating/updating a Kubernetes pipeline.  For now, it is logging a warning, but it will fail when we remove the red/black Kubernetes traffic management strategy. Change done …
=> docs(fix): change red/black to blue/green

content/en/docs/releases/release-manager-runbook/index.md
Clarify steps to release new version of Spin CLI.
=> docs(runbook): Release Manager Spin process

content/en/docs/setup/productionize/persistence/orca-sql.md
It seems that the attributes should actually be `connectionTimeoutMs` and `maxLifetimeMs`? Unless I'm misunderstanding the code x)
=> Update timeout parameters in the docs for orca-sql

config.toml, layouts/partials/head.html
[Google Analytics 4](https://support.google.com/analytics/answer/10089681?hl=en) is out and the previous solution, Google Universal Analytics, will no longer process data on July 1, 2023. 
Since we use Hugo, I took a look at the [official documentation for google analytics templates](https://gohugo.io/templates/internal/#use-the-google-analytics-template) and [community discussion about Google Analytics 4 upgrade](https://discourse.gohugo.io/t/how-to-make-site-updates-to-support-google-analytics-4/38271/4). 
I've migrated our GA to support both the old and new tag methods, so once this is merged, we should be able to see traffic in the new GA property.
Note: I have not tested this, would appreciate another set of eyes 🙏
=> chore(analytics): google analytics update

content/en/docs/releases/next-release-preview/index.md
This commit updates the next release notes to contain the artifact store feature.
https://github.com/spinnaker/kork/pull/1069
=> docs(kork): add release notes for artifact store change

content/en/docs/guides/user/pipeline/expressions/_index.md
The emphasis in link test is not displayed properly on the website,
current it looks like `<em></em>` literally.
=> Correct an emphasis in link text issue

content/en/docs/releases/release-cadence/index.md
It appears that the google calendar is no longer updated in favor of the google group, so this documentation needs updating as it is easy to miss the small alert on the versions page, subscribe to the calendar and then never receive notifications.
=> Update release cadence docs to reference the google group in addition to the google calendar.

content/en/_index.md, layouts/index.html
In the bottom gray jumbotron of the homepage, change interested in contributing text to book office hours . Add cta button with calendly link.
=> Change Jumbotron text, add cta button with calendly link

content/en/docs/guides/operator/custom-job-stages/index.md
It took me a while to get output from a custom job step working because it wasn't clear to me that "this container" implied the value should be a container name as part of the kubernetes job. My inexperience with k8s is to blame but i feel the docs could've been more explicit to push me in the right direction sooner.
It also took me a while to find the docs specifying how to actually capture the output, a link to it would've saved me a fair bit of searching around.
=> Make Custom Job output docs clearer.

config.toml, layouts/partials/google-analytics.html, layouts/partials/head.html, layouts/partials/hooks/head-end.html
After the previous change related to google analytics, https://github.com/spinnaker/spinnaker.io/pull/346, I saw a drop in traffic. I reviewed spinnaker.io using google's provided tools, via https://tagmanager.google.com/, to scan the site for tags and it did not find any. I tested this locally and was able to see my traffic hit analytics.google.com
=> fix(ga4): using tag instead of google analytics id

content/en/docs/setup/other_config/spin/index.md
Existing PowerShell command for Windows throws error when running the **Invoke-WebRequest** cmdlet.
**Error :**
```
Invoke-WebRequest : InvalidObjectNameThe specified object name is not valid.Disallowed unicode characters present in object name 'spin/1.30.0
/windows/amd64/spin.exe'
At line:1 char:1
+ Invoke-WebRequest -OutFile $env:LOCALAPPDATA\spin\spin.exe -UseBasicP ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```
**Running a quick test :**
```
Write-Output "https://storage.googleapis.com/spinnaker-artifacts/spin/$((Invoke-WebReq …
```
=> doc(install-instruction) : Fixes powershell command by removing LF character which lead to Invoke-WebRequest cmdlet erroring out

content/en/docs/reference/providers/kubernetes-v2/index.md
Pre-requisite: https://github.com/spinnaker/clouddriver/pull/5989
=> docs(kubernetes): server-side-apply strategy

content/en/docs/setup/other_config/security/authentication/x509/index.md
Adds docs on using ACM cert from https://github.com/spinnaker/spinnaker.github.io/pull/2168
=> chore(docs): ACM Certificate instructions using AWS private CA

content/en/docs/reference/pipeline/expressions/_index.md
Description:
This commit addresses an issue where a code block is incorrectly nested inside a link in the pipeline expressions documentation. By removing the code block from inside the link, the rendering of the documentation is fixed.
Closes: #422 Docs Pipeline Expressions: Issue with Code Block Rendering
=> docs(pipeline expressions): Remove Code Inside Link

content/en/changelogs/1.33.0-changelog.md, content/en/changelogs/1.33.1-changelog.md, content/en/changelogs/1.33.2-changelog.md, content/en/changelogs/1.34.0-changelog.md, content/en/changelogs/1.34.1-changelog.md, content/en/changelogs/1.34.2-changelog.md
With the liquibase 4.24.0 upgrade clouddriver and Orca were failing to start in some some scenarios. 
So updating the release notes with the details of broken functionality.
=> doc(changelog): Spinnaker Version 1.33.0 changelog updated with broken functionality info

content/en/docs/releases/next-release-preview/index.md
Kork changes: https://github.com/spinnaker/kork/pull/1199
Clouddriver changes: https://github.com/spinnaker/clouddriver/pull/6254/
=> docs(changelog): skipSpecTemplateLabels to skip applying labels to a manifest's .spec.template.metadata.labels

content/en/changelogs/1.35.0-changelog.md
Release notes for pipelineRef feature flag. PR: https://github.com/spinnaker/orca/pull/4749
The changes for pipelineRef feature flag were released as part of 1.35.0.
=> docs(sql): Include release notes for feature flag pipelineRef

content/en/changelogs/1.33.3-changelog.md, content/en/changelogs/1.34.4-changelog.md, content/en/changelogs/1.35.0-changelog.md, content/en/changelogs/1.35.1-changelog.md, content/en/changelogs/1.35.2-changelog.md
Adding a broken functionality note for the active releases that are affected from a bug in Front50 with GCS. 
Related PR for fix: https://github.com/spinnaker/front50/pull/1493
=> docs(changelog): Adding Broken functionality note for Front50 GCS

content/en/docs/releases/next-release-preview/index.md
Add change log for the PR: https://github.com/spinnaker/orca/pull/4781.
=> doc(changelog): Add changelog for an orca change

content/en/docs/setup/other_config/security/authorization/pipeline-permissions/index.md
The documentation page for [Pipeline Permissions](https://spinnaker.io/docs/setup/other_config/security/authorization/pipeline-permissions/) explains that when roles are added to a pipeline definition, only users with all of these roles can then edit or execute the pipeline. This is true about edits, since adding a privileged role there would let a user trigger an execution with privileges they don't have, but this feature does not affect manual executions. These still run with the roles and privileges of the user who triggered the pipeline manually, regardless of Pipeline Permissions.
=> fix(permissions): Pipeline permissions do not affect manual triggers

content/en/docs/releases/next-release-preview/index.md
Add changelog for the clouddriver PR - https://github.com/spinnaker/clouddriver/pull/6340 - refactor(retrofit2): replace retrofit client with retrofit2 client
=> doc(changelog): Add changelog for upgrading all retrofit clients to retrofit2

content/en/docs/setup/other_config/spin/index.md
Add the `curl` command for ARM64, see https://github.com/spinnaker/spinnaker/issues/6632
=> Docs: Add ARM64 curl example

content/en/docs/releases/next-release-preview/index.md
Add release note for https://github.com/spinnaker/igor/pull/1313 which upgrades Igor to retrofit2 and removes all references and dependencies to retrofit1
=> doc(changelog): Add release note for igor retrofit2 upgrade

layouts/shortcodes/deprecated-versions.html, layouts/shortcodes/latest-stable.html
I noticed version 1.39.10 is showing as deprecated while 1.39.9 is showing as latest.
This should fix it. I don't know if there is a case where an older version has a larger number (re-release?), but I doubt it.
Tested locally
=> fix(changelog): Fix patch versions sorting

content/en/changelogs/2025.0.0-changelog.md
so sorting works on https://spinnaker.io/docs/releases/versions/
https://github.com/spinnaker/spinnaker/pull/7047 has the fix for future releases.
=> fix(changelog): use numeric seconds in the timestamp for 2025.0.0

content/en/docs/reference/halyard/commands.md, content/en/docs/reference/providers/cloudrun.md, content/en/docs/setup/install/providers/cloudrun.md
Added cloudrun provider documentation in spinnaker.io website.
Added halyard cloudrun provider documentation in spinnaker.io website.
=> feat(provider/google): Added cloudrun provider reference documentation in spinnaker.io
