spinnaker/spinnaker.io

content/en/docs/concepts/clusters/_index.md
Add a description for the clusters doc.
=> docs(clusters): add description

content/en/docs/concepts/providers/_index.md
The old description didn't really fit the theme of the page so I'm not sure if it was some old text that didn't get updated? I updated the description in case you wanted it updated.
=> docs(providers): update description

content/en/docs/concepts/pipelines/_index.md
Add description for pipelines doc.
=> docs(pipelines): add description

content/en/docs/concepts/ebook/_index.md
Add a description for the ebook doc.
=> docs(ebook): add description

content/en/docs/guides/runbooks/orca-zombie-executions.md
Add description for ORCA zombie Executions
=> docs(orca-zombie-executions): add description

content/en/docs/guides/runbooks/orca-quality-of-service.md
Add description for ORCA quality of service
=> docs(orca-quality-of-service): add description

content/en/docs/guides/tutorials/_index.md
Add a description for tutorials.
=> docs(tutorials): add description

content/en/docs/guides/operator/hiding-stages.md
Add description for hiding stages.
=> docs(hiding-stages): add description

content/en/docs/guides/operator/custom-webhook-stages/_index.md
Add description for custom webhook stages.
=> docs(custom-webook-stages): add description

content/en/docs/guides/operator/custom-boms.md
Add description for custom BOMs.
=> docs(custom-boms): add description

content/en/docs/guides/operator/webhook-custom-trust-store.md
Add description for adding custom trusted certificate authorities.
=> docs(webhook-custom-trust-store): add description

content/en/docs/guides/operator/_index.md
Add description for operators.
=> desc(operator): add description

content/en/docs/guides/developer/new-stage.md
Add description for creating a new stage.
=> docs(new-stage): add description

content/en/docs/guides/runbooks/_index.md
=> docs(runbook): add description

content/en/docs/guides/operator/orca-redis-to-sql.md
Add description for Orca Redis to SQL migration.
=> docs(orca-redis-to-sql): add description

content/en/docs/guides/runbooks/sharding-spinnaker.md
Add description for sharding Spinnaker
=> docs(sharding-spinnaker): add description

content/en/docs/community/security/_index.md
Rewrite Spinnaker's public security policy to reflect the proposed changes described here: https://github.com/spinnaker/.github/pull/3
=> Update security and responsible disclosure policy

content/en/docs/guides/developer/plugin-creator/plugin-frontend.md, content/en/includes/plugins-spin-operator.md
This is what it fixes: https://github.com/spinnaker/spinnaker.io/pull/83#pullrequestreview-675593094
=> docs(fix): fixes the broken hugo shortcodes Fernando found

netlify.toml
Copy of https://github.com/spinnaker/spinnaker.io/pull/93 but without the updated theme.
93 was approved by brian-armory
=> docs(config): Add redirects for "other config" section

content/en/docs/setup/install/providers/kubernetes-v2/_index.md, content/en/docs/setup/install/providers/kubernetes-v2/aws-eks.md, layouts/shortcodes/link.html, package-lock.json, package.json, static/downloads/aws/managed.yaml, static/downloads/aws/managing.yaml, static/downloads/kubernetes/quick-install.yml, static/downloads/kubernetes/service-account.yml
The yaml files needed to follow the installation instructions were not migrated to the new repo. I added the files and verified that the links work.
=> docs(fix): Added the missing download folder and yaml files

content/en/docs/guides/user/plugins-users/_index.md
Modify the document for the merge problem.
=> Modify the document for the merge problem.

netlify.toml
Add redirect for the community directory
=> docs(config): Add redirect for community directory

content/en/changelogs/1.24.5-changelog.md, content/en/changelogs/1.24.6-changelog.md
Manually creating the changelog for 1.24.6
=> docs(release): add 1.24.6 changelog

content/en/docs/setup/other_config/artifacts/_index.md, content/en/docs/setup/other_config/server-group-launch-settings/_index.md, content/en/docs/setup/other_config/server-group-launch-settings/aws-ec2/_index.md, content/en/docs/setup/other_config/server-group-launch-settings/aws-ec2/launch-templates-setup.md, content/en/docs/setup/other_config/server-group-launch-settings/aws-ec2/launch-templates.md
Fixing formatting, minor changes
=> docs(aws): Fixing formatting, minor changes

content/en/docs/setup/productionize/persistence/front50-sql.md
Correct typo on reference about how to disable reads against S3
=> docs(site): Correct key to disable reads against S3 

content/en/docs/setup/other_config/spin/index.md
Relevant github commit:  https://github.com/spinnaker/spin/pull/172
=> docs(site): Document hidden google oauth2 service account for spin cli

content/en/docs/releases/next-release-preview/index.md
* the changes from the following PRs have been added here:
- https://github.com/spinnaker/clouddriver/pull/5401
- https://github.com/spinnaker/orca/pull/4150
- https://github.com/spinnaker/deck/pull/9498
=> docs(site): add release docs for a few of the upcoming features in 1.27

content/en/docs/releases/next-release-preview/index.md
The changes done in the following PR are added to the release notes: [#5512](https://github.com/spinnaker/clouddriver/pull/5512)
=> docs(site): add clouddriver sharding config change details 

content/en/docs/setup/install/providers/aws/aws-ec2.md
This change fixes the GH anchor address
=> docs(fix): Fix GH anchor

content/en/docs/setup/other_config/monitoring/_index.md
* format examples table with http://markdowntable.com
* use "None" for empty cell in account column for ApplicationsController
=> docs(monitoring): Fix and format examples table

content/en/docs/guides/developer/plugin-creator/testing/plugin-deck-test.md, content/en/docs/releases/next-release-preview/index.md, content/en/docs/releases/release-manager-runbook/index.md, content/en/docs/setup/install/providers/appengine.md, content/en/docs/setup/install/providers/gce.md, content/en/docs/setup/install/providers/kubernetes-v2/aws-eks.md, content/en/docs/setup/install/providers/kubernetes-v2/gke/index.md, content/en/docs/setup/install/providers/oracle.md, content/en/docs/setup/install/storage/_index.md, content/en/docs/setup/install/storage/gcs.md, content/en/docs/setup/productionize/caching/externalize-redis.md, content/en/docs/setup/productionize/scaling/horizontal-scaling.md
- Fix encoding issues with HTML entities inside links
- Remove extra back ticks (`` ` ``) in some code blocks
=> docs(fix): Fix various encoding issues

content/en/docs/community/contributing/code/developer-guides/plugin-creators/overview.md
=> docs(fix): fix broken link to Stage Plugin Walkthrough

content/en/docs/setup/other_config/configuration/index.md
about Spring Cloud Config Server
=> Update link to doc

content/en/docs/setup/other_config/configuration/index.md
With the current configuration for the AWS s3 profile, it doesn't actually sync. This change in the configuration fixes the problem.
=> pjoshi | Fix AWS S3 backend profile configuration

content/en/docs/releases/release-manager-runbook/index.md
Related to: https://github.com/spinnaker/spinnaker/issues/6627
Corresponding `buildtool` PR: https://github.com/spinnaker/buildtool/pull/181
Not 100% complete but it's a big push. Fresh eyes and more coffee, plus no doubt some automation and refactoring on the next iteration.
=> docs(runbook): Replace some Jenkins steps with buildtool

content/en/docs/setup/install/providers/kubernetes-v2/k8s-provider.md
Added escape for special characters in the links. Also modified link text …apture to start with "Wait...
=> Issue #185

netlify.toml
Resolves issue https://github.com/spinnaker/spinnaker.io/issues/211
=> docs(infra): Add X-frame to headers

content/en/docs/releases/release-manager-runbook/index.md
closes https://github.com/spinnaker/spinnaker/issues/6627
=> docs(runbook): Add Artifact location table to Release Manager Runbook

README.md
add where and how to enable and configure the promo banner
=> docs(readme): add section on the promo banner

static/js/promo-banner.js
Cleaned up Promo Banner JS file
=> removed promo banner bugs

content/en/docs/releases/release-manager-runbook/index.md
Closes: https://github.com/spinnaker/spinnaker/issues/6662
See https://github.com/spinnaker/spinnaker/issues/6628
=> fix(docs): Add stable tags to Halyard containers when release

content/en/docs/releases/next-release-preview/index.md
Related PR: https://github.com/spinnaker/clouddriver/pull/5609
=> Update next release preview

content/en/docs/releases/next-release-preview/index.md
Related PR: https://github.com/spinnaker/deck/pull/9793
=> Update release preview notes for Deck

content/en/docs/releases/next-release-preview/index.md
Related PRs: 
- Orca: https://github.com/spinnaker/orca/pull/4294
- Igor: https://github.com/spinnaker/igor/pull/1038
=> docs(igor/orca): Update the next release preview changelog

content/en/docs/reference/providers/_index.md
=> Fixed a typo (s/provier/provider)

content/en/docs/reference/providers/kubernetes-v2/index.md
old link: https://spinnaker.io/docs/guides/developer/crd-extensions/ -> page not found
correct one: https://www.spinnaker.io/guides/developer/extending/crd-extensions/
=> fix(link): missing /extending/

content/en/docs/releases/release-manager-runbook/index.md
- drive as much as possible with buildtool GHA
- continue to require tagging, branch creation, bumpdep validation
- remove specific days and cadence
=> docs(runbook): Update release process per new buildtool GHA

content/en/docs/releases/next-release-preview/index.md
Update the next release changelog with the changes done in Clouddriver
=> docs(clouddriver): Update the next release preview changelog

content/en/docs/releases/next-release-preview/index.md
changes from https://github.com/spinnaker/gate/pull/1610
=> docs(changelog): Add release note for gate feature to add X-SPINNAKER-* fields to response header and its configuration

content/en/docs/releases/next-release-preview/index.md
Added doc for:
spinnaker/orca#4383 and spinnaker/deck#9937
=> Dynamic rollback timeout instructions.

content/en/docs/guides/runbooks/sharding-spinnaker.md
Reword sharding doc and add example of write shards for Clouddriver introduced by https://github.com/spinnaker/orca/pull/4287
=> chore(docs): Update sharding doc for Clouddriver

content/en/docs/setup/other_config/spin/index.md
fixes https://github.com/spinnaker/spinnaker.io/issues/330
Updating deadlinks for SSL and x509 generation
=> Updating ssl and x509 deadlinks

content/en/docs/guides/user/pipeline/pipeline-templates/_index.md
Replace with bullet points and `ref` links
=> docs(fix): remove text causing rendering issue

content/en/docs/releases/next-release-preview/index.md
and the front50 changes to support it.
changes from https://github.com/spinnaker/front50/pull/1252 and https://github.com/spinnaker/echo/pull/1292
=> docs(changelog): document echo's new pipelineCache.filterFront50Pipelines flag

content/en/docs/community/contributing/code/developer-guides/dev-env/getting-set-up.md, content/en/docs/setup/install/environment.md
=> fix(docs): Broken links (404)

content/en/docs/releases/next-release-preview/index.md
Update the next release preview change log to include a new feat feature whose details can be found here: https://github.com/spinnaker/fiat/pull/1058.
=> docs(fiat): Update the next release preview change log

config.toml
=> chore(docs): Link to Spinnaker Summit 2023

content/en/docs/releases/next-release-preview/index.md
from https://github.com/spinnaker/front50/pull/1275
=> docs(changelog): document sql.healthIntervalMillis property

content/en/docs/guides/user/kubernetes-v2/deploy-helm/index.md, content/en/docs/guides/user/kubernetes-v2/kustomize-manifests/index.md, content/en/docs/releases/next-release-preview/index.md
Adds in documentation for helmfile addition to Spinnaker
Relies on https://github.com/spinnaker/deck/pull/9998
Related to https://github.com/spinnaker/spinnaker/issues/6837
=> feat-6837: add helmfile documentation

content/en/docs/releases/next-release-preview/index.md
1.32 release preview for https://github.com/spinnaker/governance/pull/335
=> docs(build): Java 17 and Gradle preview

content/en/docs/releases/next-release-preview/index.md
Release notes for https://github.com/spinnaker/echo/pull/1315
=> docs(changelog): Add Release Notes for Circuit Breaker in Rest Events

content/en/_index.md, layouts/index.html
update calendly link in call to action
=> Feature cta book office hours

content/en/changelogs/1.32.0-changelog.md
See https://github.com/spinnaker/halyard/pull/2086
=> fix(java17): fix imageVariant values in release notes

content/en/docs/setup/other_config/accounts/index.md
=> style(docs): Improve formatting

content/en/docs/releases/next-release-preview/index.md
changes from https://github.com/spinnaker/orca/pull/4620
=> docs(changelog): document sql execution compression

content/en/docs/guides/user/pipeline/triggers/bitbucket-events.md
Fix 'bithucket' typo on bitbucket-events docs
=> Fix 'bithucket' typo on bitbucket-events docs

content/en/docs/setup/install/providers/kubernetes-v2/k8s-provider.md
Relates to #98
Co-authored-by: Aimee Ukasick <aimeeu.opensource@gmail.com>
Co-authored-by: David Byron <82477955+dbyron-sf@users.noreply.github.com>
=> docs(k8s-provider.md): fix link

content/en/docs/releases/next-release-preview/index.md
=> chore(docs): Java 17 release note

content/en/docs/releases/next-release-preview/index.md
Add changelog for https://github.com/spinnaker/orca/pull/4788
=> doc(changelog): Add an orca feature details in changelog

config.toml
Replace existing Spinnaker summit 2023 playlist with Spinnaker talks @ cdCon 2024 playlist
=> fix(promobanner): update promo banner with spinnaker talks playlist from cdCon 2024

content/en/docs/releases/next-release-preview/index.md
Release notes for https://github.com/spinnaker/orca/pull/4804
=> doc(changelog): Add release notes for orca changes

content/en/docs/releases/next-release-preview/index.md
Add release note for https://github.com/spinnaker/igor/pull/1301
=> doc(changelog): Add note for Igor GCB CI improvement

content/en/docs/releases/next-release-preview/index.md
Release notes for: 
- https://github.com/spinnaker/front50/pull/1520
- https://github.com/spinnaker/orca/pull/4819
=> doc(changelog): Document feature for Disable Pipelines poller agent and API filter

content/en/docs/reference/api/swagger-ui.md
https://spinnaker.io/changelogs/1.34.0-changelog/#breaking-change-springfox-300
=> doc(swagger): Update swagger endpoint

content/en/docs/releases/next-release-preview/index.md
from https://github.com/spinnaker/clouddriver/pull/6342 and https://github.com/spinnaker/clouddriver/pull/6344
=> doc(changelog): document new AWS account-related properties

content/en/docs/releases/next-release-preview/index.md
with changes from:
- https://github.com/spinnaker/orca/pull/4833
- https://github.com/spinnaker/orca/pull/4837
- https://github.com/spinnaker/orca/pull/4838
- https://github.com/spinnaker/orca/pull/4839
- https://github.com/spinnaker/orca/pull/4840
- https://github.com/spinnaker/orca/pull/4841
=> doc(changelog): document new webhook features and backoffPeriodMs

content/en/docs/guides/operator/custom-webhook-stages/index.md
Maintained the formatting and structure of the documentation.
Added webhook testing tool section for developer's benefit
Ensured links and descriptions are correct
=> Updated formatting, added more context and improved readability

content/en/docs/releases/next-release-preview/index.md
Related PR: https://github.com/spinnaker/spinnaker/pull/7063
=> add note about `mustHaveData`  checkbox in canary config in next release page

content/en/docs/releases/next-release-preview/index.md
Add changelog for retrofit2 upgrade changes.
=> doc(changelog): Add changelog for retrofit2 upgrade changes

content/en/docs/releases/next-release-preview/index.md
Related PRs:
- https://github.com/spinnaker/spinnaker/pull/7069
- https://github.com/spinnaker/spinnaker/pull/7089
- https://github.com/spinnaker/spinnaker/pull/7113
=> docs(release-notes): Adding Helm OCI registry support to release notes

config.toml
Update the link to the cdCon 2025 playlist.
=> chore(docs): link to cdCon 2025
